### ISSUE TITLE
issue pinging arduino on this network or iphone shared network

### ISSUE THREAD

**Issue by infinityfarm** [infinityfarm/hi_how_are_you#2]
I am able to communicate with REST server running on arduino when using home network..

However, when I try it on this network, no response.

I also am trying to ping the arduino connected to shared wifi from my phone and get a response that says

Request timeout for icmp_seq 160
92 bytes from 10.128.128.128: Communication prohibited by filter
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 9a51   0 0000  40  01 2df8 10.31.242.40  172.20.10.4 

I'm hoping for some help understanding what communication prohibited by filter means, and how to get around this problem.

**Comment by harimohanraj89** [comment]
This may have to do with the security settings on the GA Guest network. Come visit me and I can put you on the GA Ed network for now to see if that fixes your problem.
