### ISSUE TITLE
Issue syncing a backbone model with db model

### ISSUE THREAD

**Issue by infinityfarm** [infinityfarm/hi_how_are_you#3]
I am trying to sync a backbone view for my device admin page (device model) with my rails device model. I've tried defining the url of the model as '/device' and '/device/1' (since what I am using as the model is a single instance of the Device class, namely that with id=1')

Neither of these approaches seems to work, as I have succeeded neither in updating the model from backbone nor in displaying model attributes using the handlebars template

@harimohanraj89 
@DrRobotmck 
see: attached screenshot
![screenshot 2015-01-26 11 27 58](https://cloud.githubusercontent.com/assets/7452164/5903274/c193af80-a54e-11e4-9bec-8e6945cf4cdc.png)

**Comment by infinityfarm** [comment]
![screenshot 2015-01-26 11 27 58](https://cloud.githubusercontent.com/assets/7452164/5903288/da39a2f6-a54e-11e4-9b37-2df8e94d855b.png)

**Comment by infinityfarm** [comment]
![screenshot 2015-01-26 11 31 15](https://cloud.githubusercontent.com/assets/7452164/5903298/e813ade0-a54e-11e4-9652-8a4869d73dee.png)

**Comment by DrRobotmck** [comment]
Can you  push your code?

**Comment by DrRobotmck** [comment]
Where is the related backbone view code?

**Comment by infinityfarm** [comment]
oh yes sorry

**Comment by infinityfarm** [comment]
pushed

**Comment by harimohanraj89** [comment]
What is the status of this issue? Resolved after our conversation?

**Comment by harimohanraj89** [comment]
Closing after our conversation.
