### ISSUE TITLE
Issue listening for model reset when model is not bound to view that im listening from

### ISSUE THREAD

**Issue by infinityfarm** [infinityfarm/hi_how_are_you#4]
I want to listen for reset of my App.deviceModel from within the processing.js view. This is because it is essential that my processing function have the correct device attributes before it makes ajax calls to the device. I have tried attaching listeners for 'reset' in the normal way on the view. I've also tried calling App.deviceModel.fetch({reset: true}) from within the update device attributes function on the admin page.
Attaching relevant screenshots.
![screenshot 2015-01-27 17 11 44](https://cloud.githubusercontent.com/assets/7452164/5928309/3b83842e-a648-11e4-816d-c3a762ce833d.png)
![screenshot 2015-01-27 17 16 43](https://cloud.githubusercontent.com/assets/7452164/5928315/47456f7a-a648-11e4-8ab8-10dd487c1d6e.png)
![screenshot 2015-01-27 17 16 43](https://cloud.githubusercontent.com/assets/7452164/5928322/4f083b0c-a648-11e4-9e89-0847531407fd.png)

**Comment by infinityfarm** [comment]
@harimohanraj89

**Comment by harimohanraj89** [comment]
Have you tried listening for a `change` event instead of a `reset` event? I'm guessing `reset` is only valid for collections.

**Comment by harimohanraj89** [comment]
It looks like you are trying to make use of the 'ip_address' before you fetch the model?

**Comment by harimohanraj89** [comment]
By setting up a listener, you are telling your view that if the model changes, then your view should then run the `updateDevice` function. However, your `updateDevice` function, is performing a `fetch` on the model.

**Comment by infinityfarm** [comment]
so I should try fetching in the initialize function before setting the listener?

**Comment by infinityfarm** [comment]
it still isnt calling the updateDevice function when I change the model from admin page for some reason

**Comment by infinityfarm** [comment]
the fetch is now happening in the init function

**Comment by harimohanraj89** [comment]
Ok. What does the updated code look like?

**Comment by infinityfarm** [comment]
![screenshot 2015-01-27 17 36 59](https://cloud.githubusercontent.com/assets/7452164/5928694/1d07e014-a64b-11e4-816b-cbe750e51674.png)

**Comment by infinityfarm** [comment]
hmm

**Comment by harimohanraj89** [comment]
You're still listening for a reset event.
Models don't fire reset events.
You'll have to listen for change events.

**Comment by infinityfarm** [comment]
ah yeah I tried that too
that doesn't work either

**Comment by infinityfarm** [comment]
I changed it back to change event right after I send this screenshot and tried it because I saw it

**Comment by infinityfarm** [comment]
still doesnt work tho

**Comment by harimohanraj89** [comment]
Is the issue that the `updateDevice` function is never called?

**Comment by infinityfarm** [comment]
it's called but only on rendering the page

**Comment by infinityfarm** [comment]
it's not getting called when the model resets which is what I want to have happen

**Comment by harimohanraj89** [comment]
Where is the code that resets the model?

**Comment by infinityfarm** [comment]
sorry i mean when the model changes

**Comment by infinityfarm** [comment]
![screenshot 2015-01-27 17 55 36](https://cloud.githubusercontent.com/assets/7452164/5928987/b7ea8940-a64d-11e4-835a-89e9a152b358.png)

**Comment by infinityfarm** [comment]
here the model changes if I update the ip address
but it is not firing a change event apparently?

**Comment by harimohanraj89** [comment]
And here, is `this.model` the same object as `App.deviceModel`?

**Comment by infinityfarm** [comment]
no

**Comment by infinityfarm** [comment]
this.model is something else

**Comment by infinityfarm** [comment]
that's why I defined the device model on App, so that I could use two models in this view

**Comment by infinityfarm** [comment]
or so I hoped..

**Comment by harimohanraj89** [comment]
If `this.model` is something else, then it will not trigger your `change` listener because your `processing` view is listening for `App.deviceModel` to change.

**Comment by infinityfarm** [comment]
oh shoot sorry

**Comment by infinityfarm** [comment]
here this.model is the same thing

**Comment by infinityfarm** [comment]
yeah and I've tried this still not working
![screenshot 2015-01-27 18 04 43](https://cloud.githubusercontent.com/assets/7452164/5929143/065f3f70-a64f-11e4-8669-02eeca338eb5.png)

**Comment by harimohanraj89** [comment]
Are you sure that the IP address you are grabbing in the `updateByClick` function is correct?

**Comment by infinityfarm** [comment]
what do you mean?

**Comment by infinityfarm** [comment]
its meant to take in whatever ip address I throw in there

**Comment by harimohanraj89** [comment]
Are you sure it's grabbing the IP address you type into the box correctly?

**Comment by infinityfarm** [comment]
yes i think it is

**Comment by infinityfarm** [comment]
I get the right IP address on processing view

**Comment by infinityfarm** [comment]
the only issue is if I change the ip address from an admin view open in a different tab

**Comment by infinityfarm** [comment]
i want processing view to refresh the ip its using

**Comment by infinityfarm** [comment]
in any other case the ip is fine

**Comment by infinityfarm** [comment]
just trying to solve an edge case

**Comment by harimohanraj89** [comment]
I see. Backbone events do not jump across different tabs. Two different tabs are as good as two different clients. The functionality you seek would involve using something like web sockets.

**Comment by infinityfarm** [comment]
ahh

**Comment by infinityfarm** [comment]
ok nevermind that for now then
